import fs from 'node:fs';
import path from 'node:path';

const file = path.join(process.cwd(), 'src', 'data', 'shop_inventory.json');
const raw = fs.readFileSync(file, 'utf8');
const data = JSON.parse(raw);

// Remove any categories that look like "Electricals Materials" variants
const filtered = data.categories.filter((c) => {
  const name = (c.category_name || '').toUpperCase();
  return !(
    name.includes('ELECTRICALS MATERIALS') ||
    name.includes('ELECTRICALS\u00A0MATERIALS') // in case of NBSP or odd spacing
  );
});

// New category payload provided by user
const newCategory = {
  category_name: 'ELECTRICALS ELECTRICALS MATERIALS',
  products: [
    { item_code: 'ADA001', item_description: 'Adaptor Box 100x100x70', price: '' },
    { item_code: 'ADA002', item_description: 'Adaptor Box 150x150x70', price: '' },
    { item_code: 'ADA003', item_description: 'Adaptor Box 200x200x80', price: '' },
    { item_code: 'ADA005', item_description: 'Adaptor Box 255x200x80mm', price: '' },
    { item_code: 'ADA006', item_description: 'Adaptor Box 300x250x120mm', price: '' },
    { item_code: 'BAL010', item_description: 'Ball Fitting Bulb', price: '' },
    { item_code: 'BEL001', item_description: 'Bell Ding Dong', price: '' },
    { item_code: 'BLA016', item_description: 'Blanking Cover Double', price: '' },
    { item_code: 'BLA017', item_description: 'Blanking Cover Single', price: '' },
    { item_code: 'BUL001', item_description: 'Bulb Energy Saver Pin 7w', price: '' },
    { item_code: 'BUL002', item_description: 'Bulb Energy Saver Pin 9w', price: '' },
    { item_code: 'BUL003', item_description: 'Bulb Energy Saver Screw 7w', price: '' },
    { item_code: 'BUL004', item_description: 'Bulb Eneryg Saver Screw 9w', price: '' },
    { item_code: 'BUL006', item_description: 'Bulb Filament 4w', price: '' },
    { item_code: 'BUL007', item_description: 'Bulb Holder Angle', price: '' },
    { item_code: 'BUL008', item_description: 'Bulb Holder Ceiling Rose', price: '' },
    { item_code: 'BUL009', item_description: 'Bulb Holder Pin', price: '' },
    { item_code: 'BUL010', item_description: 'Bulb Holder Screw', price: '' },
    { item_code: 'BUL011', item_description: 'Bulb Holder Straight', price: '' },
    { item_code: 'BUL012', item_description: 'Bulbs 100w', price: '' },
    { item_code: 'BUL013', item_description: 'Bulbs 40w', price: '' },
    { item_code: 'BUL014', item_description: 'Bulbs 60w', price: '' },
    { item_code: 'BUL015', item_description: 'Bulk Head Fitting', price: '' },
    { item_code: 'CAB001', item_description: 'Cable Clips 10mm', price: '' },
    { item_code: 'CAB002', item_description: 'Cable Clips 12mm', price: '' },
    { item_code: 'CAB003', item_description: 'Cable Clips 9mm', price: '' },
    { item_code: 'CAB005', item_description: 'Cable Clips Round 10mm', price: '' },
    { item_code: 'CAB006', item_description: 'Cable Ties 10', price: '' },
    { item_code: 'CAB007', item_description: 'Cable Ties 12', price: '' },
    { item_code: 'CAB008', item_description: 'Cable Ties 14', price: '' },
    { item_code: 'CAB009', item_description: 'Cable Ties 6', price: '' },
    { item_code: 'CAB010', item_description: 'Cable Ties 8', price: '' },
    { item_code: 'CAB011', item_description: 'Cable Ties Pcs', price: '' },
    { item_code: 'CAB013', item_description: 'CABLE TIES 4"', price: '' },
    { item_code: 'CAB014', item_description: 'Cable Clips 8mm', price: '' },
    { item_code: 'CIR001', item_description: 'Circuit Breaker Single Mcb', price: '' },
    { item_code: 'CIR005', item_description: 'Circular Box 1way 25mm', price: '' },
    { item_code: 'CIR006', item_description: 'Circular Box 2way', price: '' },
    { item_code: 'CIR007', item_description: 'Circular Box 3way 20mm', price: '' },
    { item_code: 'CIR008', item_description: 'Circular Box 3way 25mm', price: '' },
    { item_code: 'CIR009', item_description: 'Circular Box 4way 20mm', price: '' },
    { item_code: 'CIR010', item_description: 'Circular Box 4way 25mm', price: '' },
    { item_code: 'CIR011', item_description: 'Circular Box 1 way 20MM', price: '' },
    { item_code: 'CIR012', item_description: 'Circuit breaker mcb 100A', price: '' },
    { item_code: 'CON001', item_description: 'Conduit 20mm', price: '' },
    { item_code: 'CON002', item_description: 'Conduit 25mm', price: '' },
    { item_code: 'CON003', item_description: 'Conduit 32mm', price: '' },
    { item_code: 'CON004', item_description: 'Conduit 38mm', price: '' },
    { item_code: 'CON006', item_description: 'Conduit Metro 20mm', price: '' },
    { item_code: 'CON007', item_description: 'Conduit Metro 25mm', price: '' },
    { item_code: 'CON008', item_description: 'Conduit Metro 32mm', price: '' },
    { item_code: 'CON009', item_description: 'Conduit Metro 38mm', price: '' },
    { item_code: 'CON010', item_description: 'Conduit Metro 50mm', price: '' },
    { item_code: 'CON013', item_description: 'Consumer Unit 10way', price: '' },
    { item_code: 'CON014', item_description: 'Consumer Unit 14way', price: '' },
    { item_code: 'CON015', item_description: 'Consumer Unit 4way', price: '' },
    { item_code: 'CON016', item_description: 'Consumer Unit 6way', price: '' },
    { item_code: 'CON017', item_description: 'Consumer Unit 8way', price: '' },
    { item_code: 'CON018', item_description: 'Consumer Unit Havels 12way', price: '' },
    { item_code: 'CON019', item_description: 'Consumer Unit Havels 4way', price: '' },
    { item_code: 'CON020', item_description: 'Consumer Unit Havels 6way', price: '' },
    { item_code: 'CON028', item_description: 'Consumer Unit 12way', price: '' },
    { item_code: 'COO001', item_description: 'Cooker Unit H/G', price: '' },
    { item_code: 'COO002', item_description: 'Cooker Unit Socket', price: '' },
    { item_code: 'COU007', item_description: 'Coupler Threaded 20mm', price: '' },
    { item_code: 'COU008', item_description: 'Coupler Threaded 25mm', price: '' },
    { item_code: 'COU009', item_description: 'Couplers 20mm', price: '' },
    { item_code: 'COU010', item_description: 'Couplers 25mm', price: '' },
    { item_code: 'COU011', item_description: 'Couplers 32mm', price: '' },
    { item_code: 'COU012', item_description: 'Couplers 38mm', price: '' },
    { item_code: 'COU013', item_description: 'Couplers 50mm', price: '' },
    { item_code: 'CUT001', item_description: 'Cut Out Double', price: '' },
    { item_code: 'CUT002', item_description: 'Cut Out Single', price: '' },
    { item_code: 'CUT004', item_description: 'Cutout Single', price: '' },
    { item_code: 'CUT005', item_description: 'Cutout Twin', price: '' },
    { item_code: 'DOO001', item_description: 'Door Bell Ding Dong', price: '' },
    { item_code: 'DOO002', item_description: 'Door Bell Switch', price: '' },
    { item_code: 'DOO009', item_description: 'Double Pole 100a', price: '' },
    { item_code: 'DOO010', item_description: 'Double Pole 63a', price: '' },
    { item_code: 'ELE001', item_description: 'Elec Bend 20mm', price: '' },
    { item_code: 'ELE002', item_description: 'Elec Bend 25mm', price: '' },
    { item_code: 'ELE003', item_description: 'Elec Bend 32mm', price: '' },
    { item_code: 'ELE004', item_description: 'Elec Bend 38mm', price: '' },
    { item_code: 'ELE005', item_description: 'Elec Bend 50mm', price: '' },
    { item_code: 'ELE006', item_description: 'Elec Cable Flex 1.5mm mtrs', price: '' },
    { item_code: 'ELE007', item_description: 'Elec Cable Flex 2.5mm mtrs', price: '' },
    { item_code: 'ELE008', item_description: 'Elec Cable Single 1.5mm red mtr', price: '' },
    { item_code: 'ELE009', item_description: 'Elec Cable Single 1.5mm Black R', price: '' },
    { item_code: 'ELE010', item_description: 'Elec Cable Single 1.5mm Green I', price: '' },
    { item_code: 'ELE011', item_description: 'Elec Cable Single 1.5mm Red RC', price: '' },
    { item_code: 'ELE012', item_description: 'Elec Cable Single 10.0mm', price: '' },
    { item_code: 'ELE013', item_description: 'Elec Cable Single 2.5mm Red mt', price: '' },
    { item_code: 'ELE014', item_description: 'Elec Cable Single 2.5mm Black', price: '' },
    { item_code: 'ELE015', item_description: 'Elec Cable Single 2.5mm Green I', price: '' },
    { item_code: 'ELE016', item_description: 'Elec Cable Single 2.5mm Red RC', price: '' },
    { item_code: 'ELE018', item_description: 'Elec Cable Twin 1.5mm Roll Grey', price: '' },
    { item_code: 'ELE019', item_description: 'Elec Cable Twin 2.5mm Roll', price: '' },
    { item_code: 'ELE025', item_description: 'Elec Screws 4ba', price: '' },
    { item_code: 'ELE026', item_description: 'Elec Top Plug', price: '' },
    { item_code: 'ELE028', item_description: 'Electric Starter', price: '' },
    { item_code: 'ELE030', item_description: 'Element Shower', price: '' },
    { item_code: 'ELE031', item_description: 'Elec Cable Single 1.5mm Black', price: '' },
    { item_code: 'ELE032', item_description: 'Elec Cable Single 1.5mm Green', price: '' },
    { item_code: 'ELE033', item_description: 'Elec Cable Single 2.5mm Black R', price: '' },
    { item_code: 'ELE034', item_description: 'Elec Cable Single 2.5mm Green', price: '' },
    { item_code: 'ELE035', item_description: 'Elec Cable Twin 1.5mm Mtrs', price: '' },
    { item_code: 'ELE036', item_description: 'Elec Cable Twin 2.5mm Mtrs', price: '' },
    { item_code: 'ELE037', item_description: 'ELEC CABLE FLEX 1.5MM', price: '' },
    { item_code: 'ELE038', item_description: 'ELEC CABLE FLEX 2.5MM', price: '' },
    { item_code: 'ELE039', item_description: 'Elec Cable Single 4mm Black', price: '' },
    { item_code: 'EXT001', item_description: 'Extension 4way Surge', price: '' },
    { item_code: 'EXT004', item_description: 'Extension Ring', price: '' },
    { item_code: 'EXT005', item_description: 'Extension Socket 4way', price: '' },
    { item_code: 'EXT006', item_description: 'Extension Socket 6way', price: '' },
    { item_code: 'FLE001', item_description: 'Flex Conduit 25mm Mtrs', price: '' },
    { item_code: 'FLE013', item_description: 'Flex conduit 20mm Mtrs', price: '' },
    { item_code: 'FLE014', item_description: 'Flex conduit Roll 20mm black', price: '' },
    { item_code: 'FLE015', item_description: 'Flex conduit Roll 25mm black', price: '' },
    { item_code: 'FLE016', item_description: 'Flex conduit Roll 20mm White', price: '' },
    { item_code: 'FLE017', item_description: 'Flex conduit Roll 25mm white', price: '' },
    { item_code: 'FLO002', item_description: 'Flood Light Led 30w', price: '' },
    { item_code: 'FLO003', item_description: 'Flood Light Led 50w', price: '' },
    { item_code: 'FLO006', item_description: 'Flourescent Fitting 2ft', price: '' },
    { item_code: 'FLO007', item_description: 'Flourescent Fitting 4ft', price: '' },
    { item_code: 'FLO010', item_description: 'Flourescent Tube 2ft', price: '' },
    { item_code: 'FLO011', item_description: 'Flourescent Tube 4ft', price: '' },
    { item_code: 'FRI001', item_description: 'Fridge Guard', price: '' },
    { item_code: 'IND001', item_description: 'Ind Socket Single Phase', price: '' },
    { item_code: 'IND002', item_description: 'Ind Socket Three Phase', price: '' },
    { item_code: 'IND003', item_description: 'Industrial Socket Two Phase', price: '' },
    { item_code: 'INS001', item_description: 'Insulatin Tape Black Big', price: '' },
    { item_code: 'INS002', item_description: 'Insulating Tape Black Small', price: '' },
    { item_code: 'INS004', item_description: 'Insulating Tape Yellow Big', price: '' },
    { item_code: 'INS008', item_description: 'Insulating Tape White Big', price: '' },
    { item_code: 'INS012', item_description: 'Instant Shower Ener 4t', price: '' },
    { item_code: 'INS013', item_description: 'Instant Shower Fame', price: '' },
    { item_code: 'INS015', item_description: 'Instant Shower Lorenzeti', price: '' },
    { item_code: 'INS018', item_description: 'Insulating Tape Green Big', price: '' },
    { item_code: 'INS019', item_description: 'Insulating Tape Red Big', price: '' },
    { item_code: 'INT001', item_description: 'TV Outlet', price: '' },
    { item_code: 'LED001', item_description: 'Flourescent Led Fittings 2ft', price: '' },
    { item_code: 'LED002', item_description: 'Flourescent Led Fittings 4ft', price: '' },
    { item_code: 'LED003', item_description: 'Led Lights 10w', price: '' },
    { item_code: 'LED004', item_description: 'Flourescent Led Fittings 2ft', price: '' },
    { item_code: 'LED005', item_description: 'Fllourescent Led Fittings 4ft', price: '' },
    { item_code: 'LOO001', item_description: 'Looping Boxes', price: '' },
    { item_code: 'M.C001', item_description: 'M.C.B Rail', price: '' },
    { item_code: 'MAC002', item_description: 'Machine Screw 2ba pcs', price: '' },
    { item_code: 'MAC003', item_description: 'Machine Screw 4.0 Pcs', price: '' },
    { item_code: 'MAC004', item_description: 'Machine Screw 4ba', price: '' },
    { item_code: 'MAC005', item_description: 'MACHINE SCREW 2BA PKT', price: '' },
    { item_code: 'MCB001', item_description: 'Mcb 63 A D/Pole', price: '' },
    { item_code: 'MCB002', item_description: 'Mcb 20A S/Pole', price: '' },
    { item_code: 'MCB003', item_description: 'Mcb 32A S/Pole', price: '' },
    { item_code: 'MCB004', item_description: 'MCB 10 AMP', price: '' },
    { item_code: 'MCB005', item_description: 'MCB 16 AMP', price: '' },
    { item_code: 'MCB006', item_description: 'Mcb 63 A S/Pole', price: '' },
    { item_code: 'MCB007', item_description: 'Mcb 100 A D/Pole', price: '' },
    { item_code: 'MET006', item_description: 'Meter Box Powdered 13X13', price: '' },
    { item_code: 'MET007', item_description: 'Meter Box Powdered Big', price: '' },
    { item_code: 'MET008', item_description: 'Meter Liner', price: '' },
    { item_code: 'MIN001', item_description: 'Mini Trunking', price: '' },
    { item_code: 'MUL001', item_description: 'Multi Plug', price: '' },
    { item_code: 'PAT001', item_description: 'Pattress Double Deep', price: '' },
    { item_code: 'PAT002', item_description: 'Pattress Double Shallow', price: '' },
    { item_code: 'PAT003', item_description: 'Pattress Single Deep', price: '' },
    { item_code: 'PAT004', item_description: 'Pattress Single Shallow', price: '' },
    { item_code: 'PHO001', item_description: 'Photocell Switch', price: '' },
    { item_code: 'POW001', item_description: 'Power Guard', price: '' },
    { item_code: 'ROU003', item_description: 'Round Covers Black Large', price: '' },
    { item_code: 'ROU004', item_description: 'Round Covers Black Small', price: '' },
    { item_code: 'ROU005', item_description: 'Round Covers White Large', price: '' },
    { item_code: 'ROU006', item_description: 'Round Covers White Small', price: '' },
    { item_code: 'SEN001', item_description: 'Motion Sensor', price: '' },
    { item_code: 'SOC001', item_description: 'Socket Double', price: '' },
    { item_code: 'SOC002', item_description: 'Socket Single', price: '' },
    { item_code: 'STR003', item_description: 'Strip Connector 30a', price: '' },
    { item_code: 'STR004', item_description: 'Strip Connector 60a', price: '' },
    { item_code: 'STR016', item_description: 'Strip Connector 20a', price: '' },
    { item_code: 'STR017', item_description: 'Strip Connector 100a', price: '' },
    { item_code: 'SW1001', item_description: 'Switch 1 Gang', price: '' },
    { item_code: 'SW1002', item_description: 'Switch 2 Gang', price: '' },
    { item_code: 'SW1003', item_description: 'Switch 3 Gang', price: '' },
    { item_code: 'SW1004', item_description: 'Switch 4 Gang', price: '' },
    { item_code: 'SW1005', item_description: 'Switch Box Double', price: '' },
    { item_code: 'SW1006', item_description: 'Switch Box Single', price: '' },
    { item_code: 'TRO001', item_description: 'Tronic Led Fitting 4ft', price: '' },
    { item_code: 'TRO002', item_description: 'Tronic Led Tube 4ft', price: '' },
    { item_code: 'TRO010', item_description: 'Tronic Led Fitting 2ft', price: '' },
    { item_code: 'TRO011', item_description: 'Tronic Led Tube 2ft', price: '' },
    { item_code: 'TRU002', item_description: 'Trunking 25x40', price: '' },
    { item_code: 'TRU004', item_description: 'Trunking 75x50', price: '' },
    { item_code: 'WAT001', item_description: 'Water Heater Switch 20a', price: '' },
    { item_code: 'WAT002', item_description: 'Water Heater Switch 45a', price: '' },
    { item_code: 'WAT015', item_description: 'Waterproof Socket Single', price: '' },
    { item_code: 'WAT016', item_description: 'Waterproof Socket Twin', price: '' },
    { item_code: 'WAT017', item_description: 'Waterproof Switch', price: '' },
  ]
};

filtered.push(newCategory);

const out = { ...data, categories: filtered };
fs.writeFileSync(file, JSON.stringify(out, null, 2) + '\n');
console.log('Replaced electricals materials with provided list.');
